# Generated by Django 6.0 on 2026-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment'), ('reply', 'Reply'), ('reaction', 'Reaction'), ('bookmark', 'Bookmark'), ('sign_up', 'Sign Up'), ('log_in', 'Log In')], help_text='Type of action that triggered the notification', max_length=20),
        ),
    ]
